### ISSUE TITLE
how to use? 

### ISSUE THREAD

**Issue by felipeoliveiradev** [paramorph/react-html-webpack-plugin#2]
Does it compile all direct html without bundle?

**Comment by mchalapuk** [comment]
Hi @felipeoliveiradev.

This plugin only renders a single html file using component and its props provided in options.

An example of how to use this plugin can be found in https://github.com/sztukauniwersalna/parrot-layout/blob/master/hot.config.js

Closing the issue. Feel free to open it this answer is not sufficient for you.
